### ISSUE TITLE
Notification, event after validation

### ISSUE THREAD

**Issue by vincenzo-antolini-os** [IdentityServer/Thinktecture.IdentityServer3.AccessTokenValidation#19]
Hi,
I'm using UseIdentityServerBearerTokenAuthentication to validate access token in my WebApi2 backend.
Is there some Notification or Event to call the User information Endpoint after validation?
I searched code but no success.

Thanks in advance
V

**Comment by leastprivilege** [comment]
Well - userinfo is strictly speaking an OpenID Connect mechnism - not an OAuth2 one. So this would only make sense if an OIDC authentication request has been done in the first place (aka an openid scope is present). So please describe your intent in more detail.

**Comment by valeriob** [comment]
I would like this feature to enrich user claims after validation. Is there another way to do it ?

**Comment by leastprivilege** [comment]
Claims transformation

https://www.nuget.org/packages/Thinktecture.IdentityModel.Owin.ClaimsTransformation/

**Comment by valeriob** [comment]
cheers !
