### ISSUE TITLE
Question: Downloading file from SPA

### ISSUE THREAD

**Issue by remunda** [IdentityServer/Thinktecture.IdentityServer3.AccessTokenValidation#20]
Hi,

i have a question. What is the best approach for downloading files from SPA. Because i'm using bearer token authentication, i'm not able to simply open new window with url for download. Also i don't want to handle cookies in my SPA or downloading with AJAX. Is it good idea to open new window with authorization endpoint with post redirect to download URL? If so, can be used the endpoint/local validation to retrieve claims from the POST request exactly as for token in "Authorization" header?

Thanks alot for your advice

**Comment by leastprivilege** [comment]
you can read access tokens also from query strings - 

http://leastprivilege.com/2013/10/31/retrieving-bearer-tokens-from-alternative-locations-in-katanaowin/

The providers also work with the this access token middleware.

**Comment by remunda** [comment]
Great. Thanks a lot.
