### ISSUE TITLE
EpochTimeExtensions and Clock Internal

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3.AccessTokenValidation#22]
Trying to implement custom cache today I came across two classes that would be nice if they were no longer internal: 

Clock (default clock implementation) of IClock
EpochTimeExtensions

There may be others but those two required a quick copy, paste and rename for clarity on my end.

**Comment by leastprivilege** [comment]
I made Clock public. The epoch extensions should be used from a separate library (e.g. IdentityModel).
