### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication with IdentityServerV2?

### ISSUE THREAD

**Issue by eldiosyeldiablo** [IdentityServer/Thinktecture.IdentityServer3.AccessTokenValidation#23]
Is it possible to use the new UseIdentityServerBearerTokenAuthentication with our existing implementation of IdentityServerV2?

I am looking at securing our Owin WebApi applications by requiring that they receive a token with certain claims required. I see that UseIdentityServerBearerTokenAuthentication allows you to specify the Authority but I don't see a similar endpoint in V2.

I also see that it can be configured for ValidationMode.Local but I am not finding any examples for this.

**Comment by leastprivilege** [comment]
No
